from typing import List, Dict, Literal, Optional
from pydantic import BaseModel, Field


class AnalysisResult(BaseModel):
    """Result of initial code analysis by Agent 1."""
    language: str = Field(description="Detected programming language")
    purpose: str = Field(description="Overall purpose and functionality of the code")
    components: List[str] = Field(default_factory=list, description="Functions, classes, modules identified")
    risk_areas: List[str] = Field(default_factory=list, description="High risk control flows or fragile patterns")
    summary: str = Field(description="Executive summary of code structure and design")


class ReviewIssue(BaseModel):
    """An individual bug, security vulnerability, or quality issue."""
    category: Literal["Logic Bug", "Security Vulnerability", "Code Quality", "Performance", "Syntax Error"] = Field(
        description="Category of issue"
    )
    severity: Literal["CRITICAL", "HIGH", "MEDIUM", "LOW"] = Field(
        description="Severity classification"
    )
    line: int = Field(default=1, description="Line number where issue occurs (1-based)")
    title: str = Field(description="Short summary of the problem")
    description: str = Field(description="Detailed explanation of the flaw")
    impact: str = Field(description="Why it matters / operational impact")
    recommendation: str = Field(description="Suggested fix approach")
    evidence: str = Field(default="", description="Code snippet or AST trace demonstrating the issue")
    source: Literal["Deterministic (AST)", "AI Reasoning"] = Field(
        default="AI Reasoning", description="Detection source"
    )


class SeverityCounts(BaseModel):
    CRITICAL: int = 0
    HIGH: int = 0
    MEDIUM: int = 0
    LOW: int = 0


class ReviewResult(BaseModel):
    """Combined review report containing all findings."""
    summary: str = Field(description="Overall summary of the review findings")
    issues: List[ReviewIssue] = Field(default_factory=list, description="List of detected issues")
    severity_counts: SeverityCounts = Field(
        default_factory=SeverityCounts,
        description="Counts of issues by severity"
    )
    overall_assessment: str = Field(description="Pass/Fail or health assessment score/summary")


class FixResult(BaseModel):
    """Result generated by Fixing Agent (Agent 4)."""
    fixed_code: str = Field(default="", description="The complete corrected source code")
    corrected_code: Optional[str] = Field(default=None, description="The complete corrected source code")
    changes_made: List[str] = Field(default_factory=list, description="List of specific code changes made")
    explanation: str = Field(default="", description="Detailed rationale for the fixes applied")

    @property
    def code_content(self) -> str:
        return (self.corrected_code or self.fixed_code or "").strip()


class ValidationResult(BaseModel):
    """Result of independent re-review by Validator Agent (Agent 5)."""
    validation_status: Literal["PASSED AI RE-REVIEW", "ISSUES REMAINING", "NEEDS ITERATION"] = Field(
        description="Validation outcome status"
    )
    resolved_issues: List[str] = Field(default_factory=list, description="Titles of resolved issues")
    remaining_issues: List[ReviewIssue] = Field(default_factory=list, description="Unresolved or persistent issues")
    new_issues: List[ReviewIssue] = Field(default_factory=list, description="Newly introduced issues in fixed code")
    iteration_count: int = Field(default=1, description="Current loop iteration number")
    summary: str = Field(description="Validation summary and verdict")


class PipelineIteration(BaseModel):
    """Record of a single fix-validation iteration in the self-review loop."""
    iteration_number: int
    input_code: str
    fixed_code: str
    issues_before: List[ReviewIssue]
    validation_result: ValidationResult
